spring:
  quartz:
    job-store-type: memory # ??? ??? ????? ??
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10      # Quartz ? ??? ??? ?
            threadPriority: 5
